### ISSUE TITLE
Build Error: Unbound module CAst

### ISSUE THREAD

**Issue by lastland** [QuickChick/QuickChick#56]
Hi, I'm trying to build the latest QuickChick on `master` branch on my own machine, but I got:

```
File "src/quickChick.ml4", line 19, characters 15-24: 
Error: Unbound module CAst
```

Did I miss anything?

PS: I have Coq 8.6.1, OCaml 4.05.0, and ssreflect 1.6.1.

**Comment by Lysxia** [comment]
It seems `master` only builds with Coq 8.7 (this `CAst` thing being part of the upgrade).

**Comment by lastland** [comment]
OK. Code on the `coq.8.6` branch is too old for me to use (I need some new features on `master`). I can do a binary search to figure out which version works for me, but do you have any suggestions to help me narrow the search space?

**Comment by Lysxia** [comment]
It seems to start at commit d2b3660 which is only two commits away from its youngest common ancestor 8d96741 with coq.8.6.

**Comment by lastland** [comment]
Oh, actually I haven't fetched from `coq.8.6` for some time. The latest code on that branch just works for me. Thanks!
